from _typeshed import Incomplete
from bson.code import Code
from bson.codec_options import CodecOptions as CodecOptions
from pymongo import _csot, helpers_shared as helpers_shared
from pymongo.collation import validate_collation_or_none as validate_collation_or_none
from pymongo.common import (
    validate_is_document_type as validate_is_document_type,
    validate_is_mapping as validate_is_mapping,
)
from pymongo.cursor_shared import CursorType as CursorType, _Hint, _Sort
from pymongo.errors import (
    ConnectionFailure as ConnectionFailure,
    InvalidOperation as InvalidOperation,
    OperationFailure as OperationFailure,
)
from pymongo.response import PinnedResponse as PinnedResponse
from pymongo.synchronous.client_session import ClientSession as ClientSession
from pymongo.synchronous.collection import Collection as Collection
from pymongo.synchronous.helpers import next as next
from pymongo.synchronous.pool import Connection as Connection
from pymongo.typings import _CollationIn, _DocumentType
from pymongo.write_concern import validate_boolean as validate_boolean
from typing import Any, Generic, Iterable, Mapping, NoReturn, overload

class _ConnectionManager:
    conn: Connection | None
    more_to_come: Incomplete
    def __init__(self, conn: Connection, more_to_come: bool) -> None: ...
    def update_exhaust(self, more_to_come: bool) -> None: ...
    def close(self) -> None: ...

class Cursor(Generic[_DocumentType]):
    def __init__(
        self,
        collection: Collection[_DocumentType],
        filter: Mapping[str, Any] | None = None,
        projection: Mapping[str, Any] | Iterable[str] | None = None,
        skip: int = 0,
        limit: int = 0,
        no_cursor_timeout: bool = False,
        cursor_type: int = ...,
        sort: _Sort | None = None,
        allow_partial_results: bool = False,
        oplog_replay: bool = False,
        batch_size: int = 0,
        collation: _CollationIn | None = None,
        hint: _Hint | None = None,
        max_scan: int | None = None,
        max_time_ms: int | None = None,
        max: _Sort | None = None,
        min: _Sort | None = None,
        return_key: bool | None = None,
        show_record_id: bool | None = None,
        snapshot: bool | None = None,
        comment: Any | None = None,
        session: ClientSession | None = None,
        allow_disk_use: bool | None = None,
        let: bool | None = None,
    ) -> None: ...
    @property
    def collection(self) -> Collection[_DocumentType]: ...
    @property
    def retrieved(self) -> int: ...
    def __del__(self) -> None: ...
    def clone(self) -> Cursor[_DocumentType]: ...
    def add_option(self, mask: int) -> Cursor[_DocumentType]: ...
    def remove_option(self, mask: int) -> Cursor[_DocumentType]: ...
    def allow_disk_use(self, allow_disk_use: bool) -> Cursor[_DocumentType]: ...
    def limit(self, limit: int) -> Cursor[_DocumentType]: ...
    def batch_size(self, batch_size: int) -> Cursor[_DocumentType]: ...
    def skip(self, skip: int) -> Cursor[_DocumentType]: ...
    def max_time_ms(self, max_time_ms: int | None) -> Cursor[_DocumentType]: ...
    def max_await_time_ms(
        self, max_await_time_ms: int | None
    ) -> Cursor[_DocumentType]: ...
    @overload
    def __getitem__(self, index: int) -> _DocumentType: ...
    @overload
    def __getitem__(self, index: slice) -> Cursor[_DocumentType]: ...
    def max_scan(self, max_scan: int | None) -> Cursor[_DocumentType]: ...
    def max(self, spec: _Sort) -> Cursor[_DocumentType]: ...
    def min(self, spec: _Sort) -> Cursor[_DocumentType]: ...
    def sort(
        self, key_or_list: _Hint, direction: int | str | None = None
    ) -> Cursor[_DocumentType]: ...
    def explain(self) -> _DocumentType: ...
    def hint(self, index: _Hint | None) -> Cursor[_DocumentType]: ...
    def comment(self, comment: Any) -> Cursor[_DocumentType]: ...
    def where(self, code: str | Code) -> Cursor[_DocumentType]: ...
    def collation(self, collation: _CollationIn | None) -> Cursor[_DocumentType]: ...
    @property
    def alive(self) -> bool: ...
    @property
    def cursor_id(self) -> int | None: ...
    @property
    def address(self) -> tuple[str, Any] | None: ...
    @property
    def session(self) -> ClientSession | None: ...
    def __copy__(self) -> Cursor[_DocumentType]: ...
    def __deepcopy__(self, memo: Any) -> Any: ...
    def close(self) -> None: ...
    def distinct(self, key: str) -> list[Any]: ...
    def rewind(self) -> Cursor[_DocumentType]: ...
    def next(self) -> _DocumentType: ...
    def __next__(self) -> _DocumentType: ...
    def __iter__(self) -> Cursor[_DocumentType]: ...
    def __enter__(self) -> Cursor[_DocumentType]: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    @_csot.apply
    def to_list(self, length: int | None = None) -> list[_DocumentType]: ...

class RawBatchCursor(Cursor, Generic[_DocumentType]):
    def __init__(
        self, collection: Collection[_DocumentType], *args: Any, **kwargs: Any
    ) -> None: ...
    def explain(self) -> _DocumentType: ...
    def __getitem__(self, index: Any) -> NoReturn: ...
